# Generated by Django 4.1.8 on 2023-04-15 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('updateAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('hours', models.CharField(max_length=10)),
                ('repeat', models.BooleanField()),
                ('createBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('updateAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('duration', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('intensity', models.CharField(choices=[('L', 'LOW'), ('M', 'MEDIUN'), ('H', 'HIGHT')], max_length=20)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.activity')),
                ('createBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updateBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('updateAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('priority', models.CharField(choices=[('L', 'LOW'), ('M', 'MEDIUN'), ('H', 'HIGHT')], max_length=256)),
                ('status', models.BooleanField(default=True)),
                ('createBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updateBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('updateAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('duration', models.CharField(max_length=20)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.activity')),
                ('createBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updateBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('updateAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('priority', models.CharField(choices=[('L', 'LOW'), ('M', 'MEDIUN'), ('H', 'HIGHT')], max_length=256)),
                ('createBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Task.task')),
                ('updateBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('updateAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('pasos', models.IntegerField()),
                ('createBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.exercises')),
                ('updateBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('updateAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('createBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updateBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='listTask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.listtask'),
        ),
        migrations.AddField(
            model_name='activity',
            name='typeActivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.activitytype'),
        ),
        migrations.AddField(
            model_name='activity',
            name='updateBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
